version: 2

defaults: &defaults
  docker:
    -
      image: docker:18.05.0-ce-git
  working_directory: ~/repo
  steps:
    - checkout
    - setup_remote_docker
    -
      run:
        name: Build application Docker image
        command: |
          docker build --tag hadolint:$VERSION --file ./$VERSION/Dockerfile .
    -
      run:
        name: List created images
        command: |
          docker images

jobs:
  build-1.6:
    environment:
      VERSION: "1.6"
    <<: *defaults

  build-1.7:
    environment:
      VERSION: "1.6"
    <<: *defaults

  build-1.8:
    environment:
      VERSION: "1.6"
    <<: *defaults

  build-1.9:
    environment:
      VERSION: "1.6"
    <<: *defaults

  build-1.10:
    environment:
      VERSION: "1.6"
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - build-1.6
      - build-1.7
      - build-1.8
      - build-1.9
      - build-1.10
